### ISSUE TITLE
To Do: + Additional Requests

### ISSUE THREAD

**Issue by ghost** [AxolotlClient/AxolotlClient-mod#13]
To Do:

- [ ]  Add an option to switch the hand position to left or right
- [x]  Complete Motion Blur
- [x]  Redesign the options menu
- [x]  Fix inconsistency with the english strings
- [x]  Replace the old client name version with the new one of the discord rpc version info
- [ ]  Item Tooltip fix backport

Additional Feature Requests by Me:
- [ ]  Extended video settings customization like Sodium Extras or Optifine
- [ ]  A feature to change colour saturation
- [ ]  Add support to see other clients,mod loaders or vanilla players badges
- [x] #18
- [ ]  Add the logo of the client and replace buttons with the axolotl options buttons on the title screen,also a title screen branding text on the left bottom of the screen(will be done as a resource pack,not sure about the branding text)
- [ ]  Replace options buttons with a high resolution version to fit the icon of the client(idk if it will be done but its assigned as a task)

- [x] (new request,not high priority)A HUD that displays the system time

**Comment by TheKodeToad** [comment]
The options menu could either look all fancy (with HD fonts, rounded buttons), or just use Minecraft's style (probably easier).

**Comment by Finsider** [comment]
Additional Feature Requests by Me:
- [x] Fire height in First-Person view
- [x] (1.8.9) Option to remove Chat Background
- [x] (not a feature request) (not high priority) Update the 1.16.5 Version

**Comment by Sup33r** [comment]
- [x] A feature for the hud which i would use often is a Player counter for servers, which would display the number of players online on a server.

**Comment by Git-Fal7** [comment]
- [x] Addon support, to enable not only 3rd party support, but also will relieve some of the core client's codebase especially server specfic features. (this is a fairly big feature with labymod).

**Comment by HowardZHY** [comment]
- [x] Add an option to disable beacon beams.

**Comment by ghost** [comment]
- [x] Add saltlib or other optimization mod

**Comment by moehreag** [comment]
> Add saltlib or other optimization mod

This is a mod by itself, you can just put it in your mods folder!

**Comment by RoonMoonlight** [comment]
* [x] Provide server owner an option to disable certain features with Axolotl API (or similar)
Added for certain features, if more/others are needed please let us know!

**Comment by jpdisco** [comment]
- [ ] It would be nice to show the player's saturation level as another hunger bar where the air bubbles usually are when the player is not underwater

**Comment by RoonMoonlight** [comment]
* [x] Update to 1.19.4 release

**Comment by ghost** [comment]
- [x] Add 1.7 Animations

**Comment by MochaFrappMc** [comment]
> 

https://github.com/TAKfsg/oldblockhit-legacy-fabric

**Comment by ghost** [comment]
- [x] No hurt cam
- [ ] ability to remove ___ has joined the lobby messages (hypixel)
- [x] addons having their own space such as hypixel mods instead of being jammed up in the pause menu (it could become an issue with too many addons)
